watson-developer-cloud/assistant-simple

README.md, app.js, public/js/common.js, test/test.express.js
Updated code to return a message when the developer has not configured the workspace for the app.
=> Clarify when app not configured

training/car_intents.csv
@doconnor78 updating the out of scope intents. Building upon Ashima's latest work (so greetings, etc are in here too)
=> remove poor examples, add out of scope examples

README.md, manifest.yml
- Updates manifest.yml , README.md
=> Changes to README & manifest

public/css/app.css, public/js/conversation.js
=> Fix underlining with regard to responsiveness / screen resizing

training/car_workspace.json
Modified responses for TTS integration(removed multiple ellipsis)
Fixed variable names as per naming standard.
=> Fixes for TTS and var names

app.js, package.json
Now able to handle alternate_intents
=> Updated SDK version

README.md
Various edits to README based on review feedback. Condensed, resequenced, various minor tweaks.
=> Further README edits and streamlining

training/car_workspace.json
Fix for #56 
Added go_to statement in the @cuisine_bad node.
=> Fixed cuisine_bad go_to statement

training/car_workspace.json
Oliver has made changes to intents
=> Added Olivers changes to the training workspace

README.md
We did a tutorial run-through with several BlueMix first timers, and the issues that came up could be mitigated by these changes.
=> Additions and Clarity on README.md

README.md
Many of these changes were too basic for the developer audience intended
for this README. Some were kept, most reverted.
=> Revert changes from PR 82

training/car_workspace.json
- Improvements to intents and entities
- Internal Off-Topic/Mark as Irrelevant feature added to the workspace
- Off-topic intent removed
- Option selection for amenity now uses @sys-number in addition to @option
- Numeric values removed from entity @option as @sys-number handles numeric values
- If an option above 5 is chosen, user is asked to provide a valid value (system only shows 5 results on map)
- Locate restaurant now asks when user wants to travel to the restaurant
- Date/time displayed when user provides a date/time
- Time displayed in response for query "What's the time?"
- Uses server system time, not user's local time
=> Update to intents and features

public/index.html
added autofocus tag to the input box to eliminate the need to click before typing
#185
=> feat(browser): added autofocus to input box

package-lock.json, package.json, public/js/conversation.js
=> fix: Reflected Cross-site Scripting Vulnerability #199

.env.example, README.md, app.js, casper-runner.js, package-lock.json, package.json, public/js/api.js, public/js/conversation.js, test/integration/test.mainpage.js
* Added Assistant V2 API and session Id
* Updated context to latest version
* Update README.md
* Update intergration test to new bank demo
=> Added Assistant V2

package-lock.json, package.json, public/js/api.js, public/js/conversation.js
* Show server error such as  session timeout in chat window
* Enforced node >=8.15.0 to resolve 502 errors with node 6.15.0
* Added 1 second pause before scrolling chat window to fix image loading in chat window
=> Added server errors to be displayed in the chat area

public/css/app.css, public/js/conversation.js
* Added description attribute to image element and removed formatting,
as formatting for title and description can be applied in the Assistant workspace
=> Added description attribute

.eslintrc.yml, app.js
This fix address issue https://github.com/watson-developer-cloud/assistant-simple/issues/232
=> Fixed status code of 0

README.md
* Make sure all credentials are x'ed out even if they are no long correct.
=> Chore(readme): Updade readme credentials

app.js, package-lock.json, package.json, public/js/api.js, public/js/conversation.js
* Removed context as per Assistant API V2 does not require context
to be passed with each turn
=> chore(context):Removed context in line with API V2

training/bank_simple_workspace.json
* Modified Dialog in skill file to handle numeric values entered
in appointment scenario and updated Live Agent Loop
=> chore(skill):Skill File Dialog Update

.env.example, app.js, package-lock.json, package.json, public/js/api.js, public/js/conversation.js
*Update the Sample App to use the latest version
of the ibm-watson package
=> chore(SDK):Update to latest SDK
